export const mockRequests = [
  {
    id: 1,
    residentName: "Juan Dela Cruz",
    sitio: "Sitio 1",
    materialType: "Plastic Bottles",
    estimatedWeight: "2 kg",
    notes: "Clean and dry bottles",
    createdAt: "2026-03-14",
    status: "Pending",
    photoUrl: "/mock/plastic1.jpg",
  },
  {
    id: 2,
    residentName: "Maria Santos",
    sitio: "Sitio 2",
    materialType: "Cardboard",
    estimatedWeight: "5 kg",
    notes: "",
    createdAt: "2026-03-13",
    status: "Approved",
    photoUrl: "/mock/cardboard1.jpg",
  },
  {
    id: 3,
    residentName: "Pedro Ramirez",
    sitio: "Sitio 3",
    materialType: "Aluminum Cans",
    estimatedWeight: "1.5 kg",
    notes: "Mostly soda cans",
    createdAt: "2026-03-12",
    status: "For Pickup",
    photoUrl: "/mock/cans1.jpg",
  },
  {
    id: 4,
    residentName: "Ana Lopez",
    sitio: "Sitio 4",
    materialType: "Glass Bottles",
    estimatedWeight: "3 kg",
    notes: "",
    createdAt: "2026-03-11",
    status: "Completed",
    photoUrl: "/mock/glass1.jpg",
  },
  {
    id: 5,
    residentName: "Mark Villanueva",
    sitio: "Sitio 1",
    materialType: "Mixed Plastics",
    estimatedWeight: "4 kg",
    notes: "Includes containers",
    createdAt: "2026-03-10",
    status: "Pending",
    photoUrl: "/mock/plastic2.jpg",
  },
  {
    id: 6,
    residentName: "Liza Garcia",
    sitio: "Sitio 2",
    materialType: "Paper",
    estimatedWeight: "6 kg",
    notes: "",
    createdAt: "2026-03-09",
    status: "Approved",
    photoUrl: "/mock/paper1.jpg",
  },
  {
    id: 7,
    residentName: "Carlo Mendoza",
    sitio: "Sitio 3",
    materialType: "Tin Cans",
    estimatedWeight: "2 kg",
    notes: "",
    createdAt: "2026-03-08",
    status: "For Pickup",
    photoUrl: "/mock/tin1.jpg",
  },
  {
    id: 8,
    residentName: "Sofia Reyes",
    sitio: "Sitio 4",
    materialType: "Plastic Bottles",
    estimatedWeight: "3 kg",
    notes: "Separated by color",
    createdAt: "2026-03-07",
    status: "Completed",
    photoUrl: "/mock/plastic3.jpg",
  },
  {
    id: 9,
    residentName: "Ramon Bautista",
    sitio: "Sitio 5",
    materialType: "Scrap Metal",
    estimatedWeight: "8 kg",
    notes: "",
    createdAt: "2026-03-06",
    status: "Pending",
    photoUrl: "/mock/metal1.jpg",
  },
  {
    id: 10,
    residentName: "Angela Torres",
    sitio: "Sitio 2",
    materialType: "Cardboard",
    estimatedWeight: "2 kg",
    notes: "",
    createdAt: "2026-03-05",
    status: "Approved",
    photoUrl: "/mock/cardboard2.jpg",
  },
  {
    id: 11,
    residentName: "Leo Fernandez",
    sitio: "Sitio 3",
    materialType: "Plastic Containers",
    estimatedWeight: "4 kg",
    notes: "",
    createdAt: "2026-03-04",
    status: "For Pickup",
    photoUrl: "/mock/plastic4.jpg",
  },
  {
    id: 12,
    residentName: "Mia Navarro",
    sitio: "Sitio 1",
    materialType: "Glass Bottles",
    estimatedWeight: "2.5 kg",
    notes: "",
    createdAt: "2026-03-03",
    status: "Completed",
    photoUrl: "/mock/glass2.jpg",
  },
];