export const mockRequests = [
  {
    id: 1,
    residentName: "Juan Dela Cruz",
    sitio: "Sitio 1",
    materialType: "Plastic Bottles",
    estimatedWeight: "2 kg",
    actualWeight: "",
    rewardEquivalent: "",
    notes: "Clean and dry bottles",
    createdAt: "2026-03-14",
    approvedAt: "",
    pickupSchedule: "",
    scheduleStatus: "",
    collectionDate: "",
    rejectionReason: "",
    status: "requested",
    photoUrl: "/mock/plastic1.jpg",
  },
  {
    id: 2,
    residentName: "Maria Santos",
    sitio: "Sitio 2",
    materialType: "Cardboard",
    estimatedWeight: "5 kg",
    actualWeight: "",
    rewardEquivalent: "",
    notes: "",
    createdAt: "2026-03-13",
    approvedAt: "2026-03-14",
    pickupSchedule: "",
    scheduleStatus: "not-scheduled",
    collectionDate: "",
    rejectionReason: "",
    status: "approved",
    photoUrl: "/mock/cardboard1.jpg",
  },
  {
    id: 3,
    residentName: "Pedro Ramirez",
    sitio: "Sitio 3",
    materialType: "Aluminum Cans",
    estimatedWeight: "1.5 kg",
    actualWeight: "1.8 kg",
    rewardEquivalent: "1 Grocery Pack",
    notes: "Mostly soda cans",
    createdAt: "2026-03-12",
    approvedAt: "2026-03-13",
    pickupSchedule: "2026-03-14",
    scheduleStatus: "scheduled",
    collectionDate: "2026-03-14",
    rejectionReason: "",
    status: "collected",
    photoUrl: "/mock/cans1.jpg",
  },
  {
    id: 4,
    residentName: "Ana Lopez",
    sitio: "Sitio 4",
    materialType: "Glass Bottles",
    estimatedWeight: "3 kg",
    actualWeight: "",
    rewardEquivalent: "",
    notes: "",
    createdAt: "2026-03-11",
    approvedAt: "",
    pickupSchedule: "",
    scheduleStatus: "",
    collectionDate: "",
    rejectionReason: "Duplicate request",
    status: "rejected",
    photoUrl: "/mock/glass1.jpg",
  },
  {
    id: 5,
    residentName: "Mark Villanueva",
    sitio: "Sitio 1",
    materialType: "Mixed Plastics",
    estimatedWeight: "4 kg",
    actualWeight: "",
    rewardEquivalent: "",
    notes: "Includes containers",
    createdAt: "2026-03-10",
    approvedAt: "",
    pickupSchedule: "",
    scheduleStatus: "",
    collectionDate: "",
    rejectionReason: "",
    status: "requested",
    photoUrl: "/mock/plastic2.jpg",
  },
  {
    id: 6,
    residentName: "Liza Garcia",
    sitio: "Sitio 2",
    materialType: "Paper",
    estimatedWeight: "6 kg",
    actualWeight: "",
    rewardEquivalent: "",
    notes: "",
    createdAt: "2026-03-09",
    approvedAt: "2026-03-10",
    pickupSchedule: "2026-03-16",
    scheduleStatus: "scheduled",
    collectionDate: "",
    rejectionReason: "",
    status: "approved",
    photoUrl: "/mock/paper1.jpg",
  },
  {
    id: 7,
    residentName: "Carlo Mendoza",
    sitio: "Sitio 3",
    materialType: "Tin Cans",
    estimatedWeight: "2 kg",
    actualWeight: "",
    rewardEquivalent: "",
    notes: "",
    createdAt: "2026-03-08",
    approvedAt: "",
    pickupSchedule: "",
    scheduleStatus: "",
    collectionDate: "",
    rejectionReason: "",
    status: "requested",
    photoUrl: "/mock/tin1.jpg",
  },
  {
    id: 8,
    residentName: "Sofia Reyes",
    sitio: "Sitio 4",
    materialType: "Plastic Bottles",
    estimatedWeight: "3 kg",
    actualWeight: "3.2 kg",
    rewardEquivalent: "School Supplies",
    notes: "Separated by color",
    createdAt: "2026-03-07",
    approvedAt: "2026-03-08",
    pickupSchedule: "2026-03-09",
    scheduleStatus: "scheduled",
    collectionDate: "2026-03-09",
    rejectionReason: "",
    status: "collected",
    photoUrl: "/mock/plastic3.jpg",
  },
  {
    id: 9,
    residentName: "Ramon Bautista",
    sitio: "Sitio 5",
    materialType: "Scrap Metal",
    estimatedWeight: "8 kg",
    actualWeight: "",
    rewardEquivalent: "",
    notes: "",
    createdAt: "2026-03-06",
    approvedAt: "",
    pickupSchedule: "",
    scheduleStatus: "",
    collectionDate: "",
    rejectionReason: "",
    status: "requested",
    photoUrl: "/mock/metal1.jpg",
  },
  {
    id: 10,
    residentName: "Angela Torres",
    sitio: "Sitio 2",
    materialType: "Cardboard",
    estimatedWeight: "2 kg",
    actualWeight: "",
    rewardEquivalent: "",
    notes: "",
    createdAt: "2026-03-05",
    approvedAt: "2026-03-06",
    pickupSchedule: "",
    scheduleStatus: "not-scheduled",
    collectionDate: "",
    rejectionReason: "",
    status: "approved",
    photoUrl: "/mock/cardboard2.jpg",
  },
  {
    id: 11,
    residentName: "Leo Fernandez",
    sitio: "Sitio 3",
    materialType: "Plastic Containers",
    estimatedWeight: "4 kg",
    actualWeight: "",
    rewardEquivalent: "",
    notes: "",
    createdAt: "2026-03-04",
    approvedAt: "2026-03-05",
    pickupSchedule: "",
    scheduleStatus: "not-scheduled",
    collectionDate: "",
    rejectionReason: "",
    status: "approved",
    photoUrl: "/mock/plastic4.jpg",
  },
  {
    id: 12,
    residentName: "Mia Navarro",
    sitio: "Sitio 1",
    materialType: "Glass Bottles",
    estimatedWeight: "2.5 kg",
    actualWeight: "2.7 kg",
    rewardEquivalent: "Medicine Assistance",
    notes: "",
    createdAt: "2026-03-03",
    approvedAt: "2026-03-04",
    pickupSchedule: "2026-03-05",
    scheduleStatus: "scheduled",
    collectionDate: "2026-03-05",
    rejectionReason: "",
    status: "collected",
    photoUrl: "/mock/glass2.jpg",
  },
];